Implemented minize and maximize window
ContriHUB/Chrome-It pull request #35
Opened 2018-10-25 13:56 UTC by roopbiswas

Issue #12

2018-10-26 14:13 UTC, akshay31057 requested changes
wid is not initialized in the maximizing part

2018-10-26 15:37 UTC, roopbiswas commented
Sir , I have declared it in line 291 and initialized it in minise part .

2018-10-26 15:47 UTC, roopbiswas commented
@akshay31057  sir , I have made necessary changes. Please review it.

2018-11-05 22:10 UTC, akshay31057 approved these changes

2018-11-05 22:10 UTC, merged